// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3EdYIv1l2M0Brrjti-CwMVtWNyNOcFp0',
    appId: '1:349978214057:web:d7e002be1d339d2a94b3b8',
    messagingSenderId: '349978214057',
    projectId: 'flutter-app-notificacoes-unicv',
    authDomain: 'flutter-app-notificacoes-unicv.firebaseapp.com',
    databaseURL: 'https://flutter-app-notificacoes-unicv-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-notificacoes-unicv.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgtu9XNUiRe83_jtk6kOigO48fGFTzb-M',
    appId: '1:349978214057:android:69c2244adebec50494b3b8',
    messagingSenderId: '349978214057',
    projectId: 'flutter-app-notificacoes-unicv',
    databaseURL: 'https://flutter-app-notificacoes-unicv-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-notificacoes-unicv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAszvJvE8OxHDvhHzAlynr5YtpNotO4auk',
    appId: '1:349978214057:ios:41eb8041873e514c94b3b8',
    messagingSenderId: '349978214057',
    projectId: 'flutter-app-notificacoes-unicv',
    databaseURL: 'https://flutter-app-notificacoes-unicv-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-notificacoes-unicv.appspot.com',
    iosBundleId: 'com.example.telaLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAszvJvE8OxHDvhHzAlynr5YtpNotO4auk',
    appId: '1:349978214057:ios:3e0aa7d610827b5f94b3b8',
    messagingSenderId: '349978214057',
    projectId: 'flutter-app-notificacoes-unicv',
    databaseURL: 'https://flutter-app-notificacoes-unicv-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-notificacoes-unicv.appspot.com',
    iosBundleId: 'com.example.telaLogin.RunnerTests',
  );
}
